spring:
  cache:
    redis
  datasource:
    url: jdbc:mysql://127.0.0.1:3500/instagram
    username: root
    password: wjd0322189
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

#    cluster:
#      nodes: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004, 127.0.0.1:7005
#    sentinel:
#      master: mymaster
#      nodes:  127.0.0.1: 26379, 127.0.0.1: 26380, 127.0.0.1: 26381

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace


server:
  port: 8080
